esphome:
  name: tcr

esp8266:
  board: nodemcuv2

# Enable logging
logger:

i2c:
  sda: GPIO04
  scl: GPIO05
  scan: true
  frequency: 100kHz

i2c_device:
   id: tcr
   address: 0x0c

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_passwd
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Backdoor Fallback Hotspot"
    password: "7Y1J5CCDslYL"

captive_portal:

mqtt:
  broker: mosquitto.digbata.de
  username: tasmota_3
  password: !secret mqtt_passwd

text_sensor:
  - platform: template
    name: "member qr"
    icon: "mdi:qrcode"
    lambda: |-
      static struct __attribute__((packed)) result_t {
        uint16_t length;
        char content[254];
      } result;
      auto error = id(tcr).read((uint8_t*)&result, 128);
      if (error == ErrorCode::NO_ERROR && result.length > 0 && result.length < 255) {
        result.content[result.length] = '\0';
        return {str_sprintf("%s", result.content)};
      } else if (error != ErrorCode::NO_ERROR) {
        return {str_sprintf("error %d", error)};
      }
      return {};
    update_interval: 500ms

switch:
  platform: shutdown
  name: "Shutdown"